# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpenclawDiscordArchive < Formula
  desc "Archive OpenClaw Discord session transcripts to searchable vector memory"
  homepage "https://github.com/henrybloomingdale/openclaw-discord-archive"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/henrybloomingdale/openclaw-discord-archive/releases/download/v0.2.0/openclaw-discord-archive_darwin_amd64.tar.gz"
      sha256 "99eff5477b733b6c694a42fba342d1a544ee735de896df68bc9d5c438d390fc5"

      define_method(:install) do
        bin.install "openclaw-discord-archive"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/henrybloomingdale/openclaw-discord-archive/releases/download/v0.2.0/openclaw-discord-archive_darwin_arm64.tar.gz"
      sha256 "21b508b1b720948b878cc4ed480498f7eb5bc406b9465dc4f15e402d3c7bd212"

      define_method(:install) do
        bin.install "openclaw-discord-archive"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/henrybloomingdale/openclaw-discord-archive/releases/download/v0.2.0/openclaw-discord-archive_linux_amd64.tar.gz"
      sha256 "39793ea68a0373652126d8c9343abe09b4c9283a5c0ae5e88eeefb3967c52b1d"
      define_method(:install) do
        bin.install "openclaw-discord-archive"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/henrybloomingdale/openclaw-discord-archive/releases/download/v0.2.0/openclaw-discord-archive_linux_arm64.tar.gz"
      sha256 "28b8c0efa32165c1fd3cdf8ae367dc6b5633da1758d436ee614da8efb906024a"
      define_method(:install) do
        bin.install "openclaw-discord-archive"
      end
    end
  end

  test do
    assert_match "Archive OpenClaw Discord", shell_output("#{bin}/openclaw-discord-archive --help")
  end
end
