# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpenclawDiscordArchive < Formula
  desc "Archive OpenClaw Discord session transcripts to searchable vector memory"
  homepage "https://github.com/henrybloomingdale/openclaw-discord-archive"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/henrybloomingdale/openclaw-discord-archive/releases/download/v0.1.0/openclaw-discord-archive_darwin_amd64.tar.gz"
      sha256 "bcf969a0a9bd462f3ecf83c08bb0c5f54d41a5e074b39f96ee2ab7c9778560c5"

      define_method(:install) do
        bin.install "openclaw-discord-archive"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/henrybloomingdale/openclaw-discord-archive/releases/download/v0.1.0/openclaw-discord-archive_darwin_arm64.tar.gz"
      sha256 "0790a75d086d10808c60f90da3e61e6afd2d576efdc8ed7ac5bb5cc892c2f37a"

      define_method(:install) do
        bin.install "openclaw-discord-archive"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/henrybloomingdale/openclaw-discord-archive/releases/download/v0.1.0/openclaw-discord-archive_linux_amd64.tar.gz"
      sha256 "f06a46a18bb06e6953bbfec64e95ee72775c42e6e3de064ac16a7cb5a379f13c"
      define_method(:install) do
        bin.install "openclaw-discord-archive"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/henrybloomingdale/openclaw-discord-archive/releases/download/v0.1.0/openclaw-discord-archive_linux_arm64.tar.gz"
      sha256 "ab44806edb583c41894381598dcec7ef870ea6b1eb6c77174f5a93e6e65b8382"
      define_method(:install) do
        bin.install "openclaw-discord-archive"
      end
    end
  end

  test do
    assert_match "Archive OpenClaw Discord", shell_output("#{bin}/openclaw-discord-archive --help")
  end
end
